from langchain_core.messages import AIMessage, HumanMessage
from langchain_openai import ChatOpenAI
from src.workflows.state import AgentState
from dotenv import load_dotenv
import json
import os

load_dotenv()

# Using GPT-4o for the Auditor to ensure better logical reasoning
llm = ChatOpenAI(model="gpt-4o", temperature=0)

def auditor_node(state: AgentState):
    messages = state["messages"]
    user_claim = messages[0].content 
    # Use the 'evidence_text' generated by the Researcher node
    research_evidence = state.get("evidence_text", messages[-1].content)
    
    print("\n🛡️ AUDITOR: Verifying evidence quality against Local Policy...")
    
    # Updated Prompt with STRICT Compliance Rules
    system_prompt = f"""
    CRITICAL COMPLIANCE TASK:
    You are a Medicare Auditor checking if a CPT code is covered. You must be extremely strict.

    USER CLAIM: {user_claim}

    EVIDENCE FROM LOCAL PDF (Hard Truth):
    {research_evidence}

    STRICT RULES:
    1. If the evidence above explicitly lists a code as 'Non-covered', 'Excluded', or 'Non-covered Category III', the verdict MUST be FAIL.
    2. Search specifically for the CPT code mentioned in the claim (e.g., 0058T). 
    3. If 0058T is found in a non-covered list, your faithfulness_score MUST be 0.0.
    4. Do not use external knowledge. If the PDF says it is not covered, it is NOT covered.

    Return ONLY valid JSON in this exact format:
    {{
        "faithfulness_score": 0.0,
        "verdict": "FAIL",
        "supported_claims": 0,
        "unsupported_claims": 1,
        "issues": ["Code found in non-covered list"],
        "needs_web_search": false
    }}
    """
    
    response = llm.invoke([HumanMessage(content=system_prompt)])
    
    try:
        # Clean the response content in case the LLM adds markdown backticks
        raw_content = response.content.strip().replace("```json", "").replace("```", "")
        audit_result = json.loads(raw_content)
        
        # Double-check: If the evidence contains "noncovered" and the LLM missed it, force a FAIL
        evidence_lower = research_evidence.lower()
        if "noncovered" in evidence_lower or "non-covered" in evidence_lower:
            if "0058t" in evidence_lower:
                audit_result["faithfulness_score"] = 0.0
                audit_result["verdict"] = "FAIL"
                audit_result["issues"].append("Manual Override: Non-covered code detected in text.")

    except json.JSONDecodeError:
        print("   ⚠️ Failed to parse JSON - Falling back to safe defaults")
        audit_result = {
            "faithfulness_score": 0.0,
            "verdict": "FAIL",
            "issues": ["JSON Parsing Error"],
            "needs_web_search": True
        }
    
    print(f"   📊 Final Faithfulness: {audit_result['faithfulness_score']:.2f}")
    print(f"   📊 Final Verdict: {audit_result['verdict']}")
    
    verdict_msg = f"AUDIT VERDICT: {audit_result['verdict']} (Score: {audit_result['faithfulness_score']:.2f})"
    
    return {
        "messages": [AIMessage(content=verdict_msg)],
        "audit_result": audit_result,
        "needs_web_search": audit_result.get("needs_web_search", False)
    }